// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxpccfvyuymzmcuqoksf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4cGNjZnZ5dXltem1jdXFva3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NjQ1MjMsImV4cCI6MjA1NTI0MDUyM30.q1u3uD6zhYkB0wuCyb3gCUndgxc3POl7SIMMskEDd1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);